/**
 * Generated by orval 7.3.0
 */

export type AccommodationsParams = {
Name?: string;
ZipCode?: string;
City?: string;
Region?: string;
Country?: string;
MinLatitude?: number;
MaxLatitude?: number;
MinLongitude?: number;
MaxLongitude?: number;
MinPricePerNight?: number;
MaxPricePerNight?: number;
};
