/**
 * Generated by orval 7.3.0
 */

export type AccommodationsParams = {
Query?: string;
City?: string;
Region?: string;
DateFrom?: string;
DateTo?: string;
Guests?: number;
MinPricePerNight?: number;
MaxPricePerNight?: number;
Amenities?: string;
MinRating?: number;
SortBy?: string;
SortDirection?: string;
RecordNo?: number;
Offset?: number;
};
