/**
 * Generated by orval 7.3.0
 */
import type { ReviewDto } from './reviewDto';
import type { DateRangeDto } from './dateRangeDto';

export interface AccommodationDto {
  /** @nullable */
  amenities: string[];
  /** @nullable */
  city: string;
  /** @nullable */
  description?: string;
  id?: number;
  /** @nullable */
  images: string[];
  latitude: number;
  longitude: number;
  /** @nullable */
  name: string;
  pricePerNight: number;
  /** @nullable */
  rating?: number;
  /** @nullable */
  region: string;
  /** @nullable */
  reviews: ReviewDto[];
  /** @nullable */
  street: string;
  streetNumber: number;
  /** @nullable */
  unavailableDates: DateRangeDto[];
  /** @nullable */
  zipCode: string;
}
