/**
 * Generated by orval 7.3.0
 */

export type AccommodationsParams = {
Query?: string;
Name?: string;
ZipCode?: string;
City?: string;
Region?: string;
Country?: string;
MinLatitude?: number;
MaxLatitude?: number;
MinLongitude?: number;
MaxLongitude?: number;
MinPricePerNight?: number;
MaxPricePerNight?: number;
SortBy?: string;
SortDirection?: string;
Offset?: number;
RecordNo?: number;
};
