/**
 * Generated by orval 7.3.0
 */

export interface AccommodationDto {
  /** @nullable */
  city: string;
  /** @nullable */
  description?: string;
  id?: number;
  /** @nullable */
  images: string[];
  latitude: number;
  longitude: number;
  /** @nullable */
  name: string;
  pricePerNight: number;
  /** @nullable */
  rating?: number;
  /** @nullable */
  region: string;
  /** @nullable */
  street: string;
  streetNumber: number;
  /** @nullable */
  zipCode: string;
}
