/**
 * Generated by orval 7.3.0
 */

export interface AccommodationDto {
  /** @nullable */
  city: string;
  /** @nullable */
  country: string;
  /** @nullable */
  description?: string;
  id?: number;
  /** @nullable */
  image?: string;
  latitude: number;
  longitude: number;
  /** @nullable */
  name: string;
  pricePerNight: number;
  /** @nullable */
  region: string;
  /** @nullable */
  zipCode: string;
}
