/**
 * Generated by orval 7.3.0
 */

export interface AddBookingRequest {
  checkInDate: string;
  checkOutDate: string;
  /** @nullable */
  email: string;
  /** @nullable */
  name: string;
  /** @nullable */
  phoneNumber: string;
}
