/**
 * Generated by orval 7.3.0
 */
import type { BookingDto } from './bookingDto';

export interface AddBookingResponse {
  booking?: BookingDto;
  /** @nullable */
  message?: string;
  success?: boolean;
}
