/**
 * Generated by orval 7.3.0
 */

export interface BookingDto {
  accommodationId: number;
  bookingStatus: number;
  endDate: string;
  guests: number;
  id?: number;
  /** @nullable */
  paymentId?: number;
  startDate: string;
  userId: number;
}
