/**
 * Generated by orval 7.3.0
 */
import type { AccommodationDto } from './accommodationDto';

export interface GetAccommodationResponse {
  accommodation?: AccommodationDto;
  success?: boolean;
}
