/**
 * Generated by orval 7.3.0
 */
import type { AccommodationDto } from './accommodationDto';

export interface GetAccommodationsResponse {
  /** @nullable */
  accommodations: AccommodationDto[];
  totalRecords: number;
}
