/**
 * Generated by orval 7.3.0
 */
import type { BookingDto } from './bookingDto';

export interface GetBookingsResponse {
  /** @nullable */
  bookings?: BookingDto[];
  /** @nullable */
  message?: string;
  success?: boolean;
}
