/**
 * Generated by orval 7.3.0
 */
import type { AccommodationDto } from './accommodationDto';

export interface GetFavoritesResponse {
  /** @nullable */
  accommodations?: AccommodationDto[];
  /** @nullable */
  message?: string;
  success?: boolean;
}
