/**
 * Generated by orval 7.3.0
 */
import {
  HttpClient
} from '@angular/common/http'
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http'
import {
  Injectable
} from '@angular/core'
import {
  Observable
} from 'rxjs'
import type {
  CancelBookingResponse
} from '../../model'


type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class BookingsApiService {
  constructor(
    private http: HttpClient,
  ) {} cancelBooking<TData = CancelBookingResponse>(
    id: number, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    cancelBooking<TData = CancelBookingResponse>(
    id: number, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    cancelBooking<TData = CancelBookingResponse>(
    id: number, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;cancelBooking<TData = CancelBookingResponse>(
    id: number, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `/bookings/${id}/cancel`,undefined,options
    );
  }
};

export type CancelBookingClientResult = NonNullable<CancelBookingResponse>
