/**
 * Generated by orval 7.3.0
 */
import {
  HttpClient
} from '@angular/common/http'
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http'
import {
  Injectable
} from '@angular/core'
import {
  Observable
} from 'rxjs'
import type {
  CheckOrAddUserCommand,
  CheckOrAddUserResponse
} from '../../model'


type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class UsersApiService {
  constructor(
    private http: HttpClient,
  ) {} checkOrAddUser<TData = CheckOrAddUserResponse>(
    checkOrAddUserCommand: CheckOrAddUserCommand, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    checkOrAddUser<TData = CheckOrAddUserResponse>(
    checkOrAddUserCommand: CheckOrAddUserCommand, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    checkOrAddUser<TData = CheckOrAddUserResponse>(
    checkOrAddUserCommand: CheckOrAddUserCommand, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;checkOrAddUser<TData = CheckOrAddUserResponse>(
    checkOrAddUserCommand: CheckOrAddUserCommand, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `/users/checkOrAddUser`,
      checkOrAddUserCommand,options
    );
  }
};

export type CheckOrAddUserClientResult = NonNullable<CheckOrAddUserResponse>
